#**This Notebook Shows How to use Agents to Interact with Pandas DataFrame**

#**In LangChain, the Agent can access many dataframes at once**

#**Step 01: Install All the Required Packages**

In [1]:
#!pip install langchain
#!pip install watermark
#!pip install langchain-openai
#!pip install langchain_experimental
#!pip install tabulate
#!pip install langchain-google-genai

#**Step 02: Import All The Required Libraries**

In [2]:
import os
import warnings
import pandas as pd
warnings.filterwarnings('ignore')

In [4]:
from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_openai import ChatOpenAI

In [5]:
#from langchain.agents import initialize_agent
#from langchain.openai import OpenAI
from langchain_openai import OpenAI

In [6]:
import pandas as pd

#**Step 03: Setup the Environment**

In [ ]:
os.environ['GOOGLE_API_KEY'] = "google api key here"

#**Step 04: Visualize the Data**

In [8]:
df=pd.read_csv(r'C:\Users\Admin\Desktop\pyth\..G\llm.agent\titanic.csv')
print(df.shape)
df.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#**Step 05: Single DataFrame Example**

#**Agent can interact with Single DataFrame**

In [10]:
# llm=OpenAI()

In [11]:
#from langchain_openai import ChatOpenAI
from langchain_google_genai import ChatGoogleGenerativeAI

In [12]:
llm = ChatGoogleGenerativeAI(
model="gemini-2.5-flash",temperature=1)

In [13]:
agent = create_pandas_dataframe_agent(
llm,
df,
verbose=True,
agent_type="openai-tools",
allow_dangerous_code=True
)

In [14]:
agent.run("How many rows are there")

C:\Users\Admin\AppData\Local\Temp\ipykernel_5652\1005132620.py:1: LangChainDeprecationWarning: The method `Chain.run` was deprecated in langchain-classic 0.1.0 and will be removed in 1.0. Use `invoke` instead.
  agent.run("How many rows are there")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'df.shape[0]'}`


891[{'type': 'text', 'text': 'There are 891 rows.', 'extras': {'signature': 'Cl0Bvj72+wWGid8b4srCJ5RDkYw18ATb6lRR0Zz6ey4KeIpQMrdiJRFYaEa0kz+YLvaiC3Sd9CIkSVRgUdXMSQq2BDKWrJIBLE2QW2GAuGtISVN1fhMJ7NEDW5F7l7wKbgG+Pvb76Q7AdYj9/ygpGc9ykXSo5JIZPVQUN+vFNKiUj+NVdYlIoizdmVpgcWNcqJKFB4+g7z3ktFdZ8O5Qgnd0ky5NcKBoxRl+mAy1mxh+CIgey10iXKuWrceldezxni/oBTo+unXVRS3ccRbL'}, 'index': 0}]

> Finished chain.

[{'type': 'text',
  'text': 'There are 891 rows.',
  'extras': {'signature': 'Cl0Bvj72+wWGid8b4srCJ5RDkYw18ATb6lRR0Zz6ey4KeIpQMrdiJRFYaEa0kz+YLvaiC3Sd9CIkSVRgUdXMSQq2BDKWrJIBLE2QW2GAuGtISVN1fhMJ7NEDW5F7l7wKbgG+Pvb76Q7AdYj9/ygpGc9ykXSo5JIZPVQUN+vFNKiUj+NVdYlIoizdmVpgcWNcqJKFB4+g7z3ktFdZ8O5Qgnd0ky5NcKBoxRl+mAy1mxh+CIgey10iXKuWrceldezxni/oBTo+unXVRS3ccRbL'},
  'index': 0}]

In [15]:
agent.run("How many people have more than 3 siblings")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df[df['SibSp'] > 3].shape[0]"}`


30There are 30 people who have more than 3 siblings.

> Finished chain.

'There are 30 people who have more than 3 siblings.'

#**Step 06: Multi DataFrame Example**

#**Agent can also interact with Multiple DataFrames passed in a list**

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [17]:
df1=df.copy()

In [18]:
df1["Age"] = df1["Age"].fillna(df1["Age"].mean())

In [28]:
agent = create_pandas_dataframe_agent(
llm,
[df, df1],
verbose=True,
agent_type="openai-tools",
allow_dangerous_code=True
)

In [21]:
agent.run("How many rows in the age column are different")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df1['Age'].nunique()"}`


88There are 88 different values in the `Age` column.

> Finished chain.

'There are 88 different values in the `Age` column.'

In [22]:
df2=df1.copy()

In [23]:
df2["Age_Multiplied"]=df1["Age"] * 2

In [24]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Multiplied
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0

In [26]:
agent = create_pandas_dataframe_agent(
llm,
[df,df1,df2],
verbose=True,
agent_type="openai-tools",
allow_dangerous_code=True
)

In [27]:
agent.run("Are the number of columns same in all the dataframe")

> Entering new AgentExecutor chain...


> Finished chain.

''

#LANGCHAIN, PANDAS, AGENT